sudo: required
dist: trusty
language: node_js
node_js:
  - '5'

npm:
  - '3'

cache:
  directories:
    - node_modules
    - libs

script: ./scripts/.build.sh

after_success: ./scripts/.coverage.sh

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/9a9f972a1225d28e0f05
    on_success: change
    on_failure: always
    on_start: never
