sudo: required
dist: trusty
language: node_js
node_js:
  - '5'

npm:
  - '3'

cache:
  directories:
    - node_modules

before_install:
  - 'npm install -g typings bower webpack karma typescript'

script: ./scripts/.build.sh

after_success: ./scripts/.coverage.sh
